import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import '../styles/global.css'
import { TaskStoreProvider } from '../providers/task.store'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="min-[110vh]:">
      <body className={inter.className}>
        <TaskStoreProvider>
          <div className="bg-[#f5e0dc]">{children}</div>
        </TaskStoreProvider>
      </body>
    </html>
  )
}
