import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import { ReactQueryClientProvider } from '@app/components/ReactQueryProvider'

import '../styles/global.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <ReactQueryClientProvider>
      <html lang="en" className="min-[110vh]:">
        <body className={inter.className}>
          <div className="bg-[#f5e0dc]">{children}</div>
        </body>
      </html>
    </ReactQueryClientProvider>
  )
}
